import Navbar from "@/Components/(shared)/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footar from "@/Components/(shared)/Footar/Footar";
import { ThemeProvider } from "../../context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Learning Next || Insight",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <div className="Pagecss">
            <Navbar></Navbar>
            {children}
            <Footar></Footar>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
